name = "Genesis Server"
author = "Chema"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42fdcaa0af5fdbd23099045215093add039ed0f9a09c1ca5c5dc49cd084a6a6a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
