name = "Genesis Server"
author = "Chema"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fc8ae717e5a3dc67771615d3b9fae11b1810d418d5cbce0845dcf4f5747be9b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
