name = "Genesis Server"
author = "Chema"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "730603171c60ba78d4c9a3b866464820f531b525e200e74f62a0a742a20edf42"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
